# Copyright (c) 2025 Electronic Materials Office Ltd.
# SPDX-License-Identifier: MIT

---
include:
  - board: altar_i@us
    artifact-name: altar_i_us
  - board: altar_i@us
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: altar_i_us_studio

  - board: altar_i@uk
    artifact-name: altar_i_uk
  - board: altar_i@uk
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: altar_i_uk_studio
