# Copyright (c) 2025 Electronic Materials Office Limited
# SPDX-License-Identifier: MIT

---
include:
  - board: altar_i@us
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: altar_i_us_v3.0.0
  - board: altar_i@uk
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: altar_i_uk_v3.0.0
  - board: nice_nano
    shield: settings_reset
